title: J-Play Open Source
description: The J-Play app goes Open Source
baseurl: "/jplay-website"
url: "" # Votre URL GitHub Pages

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude ces fichiers du build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Variables personnalisées (vous pouvez les utiliser dans vos pages)
github_repo: "https://github.com/Pjoooo/jplay-opensource/"
discord_link: "https://discord.gg/TTyRutPKxC"
youtube_channel: "https://www.youtube.com/channel/UCl-AqtfwG96e9GidTT5WkXA"
contact_email: "pascal@cutthemustard.fr"




