title: J-Play Open Source
description: L'instrument de musique accessible à tous continue son aventure
baseurl: "/skills-github-pages" # Laissez vide si le repo s'appelle username.github.io, sinon mettez "/nom-du-repo"
url: "" # Votre URL GitHub Pages

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude ces fichiers du build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Variables personnalisées (vous pouvez les utiliser dans vos pages)
github_repo: "https://github.com/Pjoooo/skills-github-pages/"
discord_link: "https://discord.gg/6zSnSUtJ"
youtube_channel: "https://www.youtube.com/channel/UCl-AqtfwG96e9GidTT5WkXA"
contact_email: "pascal@cutthemustard.fr"


